### ISSUE TITLE
Update dev/3.0.x documentation

### ISSUE THREAD

**Issue by bobeagan** [synapsestudios/kohana-notices#12]
Reported by @boxyman:

Am I mistaken or does the documetation not match for the dev/3.0.x branch?

E.g. <?php echo Notices::display() ?> doesn't work and I cannot see the function anywhere in the source code.

Anyways dev/2.1 seems to work fine with Kohana 3.1.3.1

Thanks.

**Comment by plweil** [comment]
I'd love to be able to use this, but it's not working for me either in Kohana 3.1 (neither is dev/2.1, which returns an error). I don't see a display() function or anything similar. Am I missing something?

**Comment by bobeagan** [comment]
Yeah, this issue was created because the docs (and the demo included in the code) are outdated from refactoring that started around Kohana version 3.0 for this module.  It is on our list to update this.

**Comment by plweil** [comment]
Ok, thanks for the quick reply. If it's just the docs and the demo, then, can this be used with Kohana 3.1, and if so, what is the equivalent of Notice::display()? Thanks s.

**Comment by bobeagan** [comment]
You just use `Notices::get()` to retrieve all of the notices.  We use KOstache and pass the notices into our layout template using a function like this:

``` php
    public function notices()
    {
        $data = array();

        foreach (Notices::get() as $array)
        {
            $message_path = $array['type'].'.'.$array['key'];
            $data[] = array(
                'type'     => $array['type'],
                'key'      => $array['key'],
                'message'  => Kohana::message('notices', $message_path, 'notices.'.$message_path),
            );
        }

        return $data;
    }
```

Then you can output in your mustache file with something like this:

```
{{#notices}}
    <div class="notice {{type}}">{{message}}</div>
{/notices}}
```

Additionally, you can limit the types of notices returned when you call `Notices::get()` by passing in a string or array of the type(s) you want.
